########################################################
#Path to root directory relative to where analysis script is executed from
rootpath : '../'

#Parameters for loading up data from raw snpytxtfiles
load_data_parameters :
  #Exclude these files because snpy fails to load due to filters
  exclude_paths : ['RATIR/snpytxtfiles/14yw_snpy.txt','CfA/snpytxtfiles/SN2009dc_snpy.txt']

  #i.e. when all lcs available, pick CSP over CfA over RATIR over Avelino over Misc
  Pecking_Order : ['CSP','CfA','RATIR','AvelinoM20','Misc']

  load_path_file_survey : [['cspdr3/snpytxtfiles/','snpy_SNS_CSP.pkl','CSP'],
                ['CfA/snpytxtfiles/','snpy_SNS_CfA.pkl','CfA'],
                ['RATIR/snpytxtfiles/','snpy_SNS_RATIR.pkl','RATIR'],
                ['BayeSNLCs/snpytxtfiles/','snpy_SNS_Avelino.pkl','AvelinoM20'],
                ['Misc/snpytxtfiles/','snpy_SNS_Misc.pkl','Misc']]


  #Way in which we load up data for analysis
  #load_mode : 'preproc'   #Load up dict of snpy files OR snanalcs, useful for determining fiducial sample, this mode doesn't save snana lcs in analysis folder
  load_mode : 'analysis'   #

  #If True, manually overwrite pre-existing snana files
  #rewrite_snana : True
  rewrite_snana : False
########################################################
snpy_parameters:
  #SNooPy Parameters Here
  #Apply SNRCut or not
  #apply_SNR_cut : False
  apply_SNR_cut : True
  #SNRCut
  snrcut  : 3

  #Which snpy_model and shape parameter to use (stick to these pairs)
  #snpy_model : 'EBV_model'
  #snpy_shape : 'dm15'
  #snpy_model : 'EBV_model2'
  #snpy_shape : 'st'
  #Default Choice here
  snpy_model : False
  snpy_shape : False

  #Method for applying Milky Way Extinction Corrections
  #apply_EBVMW_corrections : False
  #apply_EBVMW_corrections : 'Presubtract' #if Presubtract applies corrections before snpy fitting, and can assume any dust law in extinction package
  apply_EBVMW_corrections : 'Model'       #if Model, use SNooPys EBVMW corrections

  #~~~#Only if EBVMW is set to 'Presubtract' are these used
  #Value of RV used in Milky Way
  RVMW    : 3.1
  #If Presubtracting Milky Way Dust Extintion, need to define a dust law for this
  #dustlaw : 'ccm89_o94'
  #dustlaw : 'ccm89'
  dustlaw : 'fitzpatrick99'
  #~~~

  #Can specify a value of Tmax during snpy fitting
  #insert_pre_defined_Tmax : True
  insert_pre_defined_Tmax : False

  #Kcorrections
  #Whether to apply it or not
  #apply_K_corrections     : False
  apply_K_corrections     : True

  #Whether to mangle or not
  #mangle : False
  mangle : True

  #Interpolation Filters
  #interpflts    : 'all'
  #interpflts    : 'BVriJH'
  interpflts    : 'uBgVriYJH'
########################################################
preproc_parameters:
  #passband list, used for extracting magnitude measurements
  pblist : ['B','V','r','i','J','H']
  #List of phases to interpolate to
  tilist     : [0]
  #The python index in tclist taken as reference time
  tref_index : 0

  #Defines extra features beyond those in pblist,tilist to extract
  #Extra_Features          : {}
  Extra_Features          : {15:['B']}

  #Factor to boost flux errors by for improved GP fitting stability
  #error_boost_dict : {}
  error_boost_dict : {1.5:['13azs','16abc'],2:['13dkx'],5:['16auf'],7:['14gnl']}

  #Arbitrary choice of string for denoting errors in mags pandas df
  errstr     : err

  #The reference passband
  ref_band        : B
  #The phase window either side of initial Tmax guess for estimating Tmax
  tmax_window     : 5
  #Resolution in time grid for estimating Tmax
  tmax_resolution : 0.01
  #No. of GP draws for estimating Tmax
  Ngpdraws        : 1000

  #Choice of Tmax
  Tmaxchoicestr : 'Tmax_snpy_fitted'
  Tmaxchoicestr : 'Tmax_GP_restframe'

  #Choice of whether to use 1DGP or 2DGP Tmax
  #Tmax_method : 'method'
  #Tmax_method : '2DGP'
  Tmax_method : '1DGP'

  #Ways of trimming data on phases; dp is time grid for GP
  phasemin : -10
  phasemax : 40
  dp       : 1

  #Trim sample params
  #Require points at refband at max
  trim_on_refband_max : True
  #Require points in other bands in pblist
  trim_on_pblist      : True
  #Require points at other phases/times
  trim_on_extras      : False

  #Maximum allowed uncertainty in Tmax estimate
  Tmax_stdmax         : 2 #0.25

  #Defines required number of points around ref_band and tc==0
  #Nbeforemax  : [0]
  #Nbeforegap  : [10]
  #Naftermax   : [1,2]
  #Naftergap   : [5,40]
  #Nbeforemax  : [0,2]
  #Nbeforegap  : [5,10]
  #Naftermax   : [0,2]
  #Naftergap   : [10,40]
  Nbeforemax  : [2]
  Nbeforegap  : [10]
  Naftermax   : [2]
  Naftergap   : [40]

  #Defines required number of points around all bands in pblist/tilist
  #Nbefore_local     : [0]
  #Nbeforegap_local  : [10]
  #Nafter_local      : [1,2]
  #Naftergap_local   : [5,40]
  #Nbefore_local     : [0,1]
  #Nbeforegap_local  : [5,10]
  #Nafter_local      : [0,1]
  #Naftergap_local   : [10,40]
  Nbefore_local     : [1]
  Nbeforegap_local  : [10]
  Nafter_local      : [1]
  Naftergap_local   : [40]

  #Defines required number of points around extra features
  Nbefore_local_extra     : [1]
  Nbeforegap_local_extra  : [15]
  Nafter_local_extra      : [1]
  Naftergap_local_extra   : [15]

  #Interpolate in either flux or mag space
  #bright_mode : flux
  bright_mode : mag

  #Method for interpolating light curves to extract magnitudes
  mags_method : '1DGP'
  mags_method : '2DGP'
########################################################
additional_cut_parameters:
  #Cuts on Sample for Stan Fitting
  #logMcut   : 10.42
  logMcut   : 10

  #mass_mode : 'low_masses'
  #mass_mode : 'high_masses'
  mass_mode : 'all_masses'

  #BVcut     : True
  BVcut     : False

  #magerrcut   : False
  magerrcut   : 0.3

  #spectype  : 'all'
  spectype  : 'normal'

  extra_drop_SNe : {'2008gb':'Removing 2008gb because (only sometimes) 2DGP-mag returns large mag. measurement error. Also Tmax is not obvious on visual inspection.'}
########################################################
analysis_parameters:
  #key for saving analysis files
  savekey  : 'fiducial'

  #Lower and upper bounds on muRV
  muRVmin   : 1
  muRVmax   : 5
  #Lower and upper bounds on individual RVs parameters
  RVsmin : 1
  RVsmax : 'inf'
  #Dispersion of Half-normal prior on sigmaRV
  disp_sigmaRV : 2
  #Dispersion on HalfCauchy prior on intrinsic mags/colours
  a_sigma_mint : 1
  a_sigma_cint : 1

  #Data that is fed into model
  DataTransformation : 'B-X'
  DataTransformation : 'X-H'
  DataTransformation : 'Adjacent'
  DataTransformation : 'mags'

  #Reference frame in which hyperpriors are placed to model intrinsic chromatic variations
  IntrinsicModel : 'B-X'
  IntrinsicModel : 'X-H'
  IntrinsicModel : 'Adjacent'
  IntrinsicModel : 'Deviations'

  #Population distribution of AVs prior
  AVprior : 'Gamma'
  AVprior : 'exp'

  #Choice of effective wavelengths
  lam_choice : 'effective_thetaOFF'
  lam_choice : 'effective_thetaOFFepsOFF'
  lam_choice : 'central'
  lam_choice : 'effective_taustar'
  lam_choice : 'effective_thetaON'

  #Choice of whether to include dm15B in model or not
  include_LCshape : True
  include_LCshape : False

  #Choice of whether to include SN-to-SN intrinsic variations
  include_residuals : False
  include_residuals : True

  #Choice of whether to include censored data in the model
  CensoredData : True
  CensoredData : False

  #Upper bound on B-V where SNe within 0.3<B-V<CensoredCut will be included as CensoredData, those above CensoredCut are cut from sample entirely.
  CensoredCut : 1.0
  CensoredCut : 'inf'

  #Option to make multiple copies of sample to fit
  copymode : 1
  copymode : False

  #Stan Samples Here
  n_warmup   : 1000
  n_sampling : 1000
  n_chains   : 4
  n_thin     : 1000
  random_seed : 10000
########################################################
plotting_parameters :
  #Fontsize
  FS   : 18

  #Show plot
  show : False
  show : True

  #Save plot
  save : True
